# from pluralsight

In [1]:
import torch
print(torch.__version__)

1.13.0


In [2]:
tensor_array = torch.Tensor([[1,2],[4,5]])
tensor_array


tensor([[1., 2.],
        [4., 5.]])

In [3]:
tensor_uninitialized = torch.Tensor(3,3)

In [4]:
tensor_uninitialized

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.numel(tensor_uninitialized)

9

In [8]:
tensor_initialized = torch.rand(2,3)
tensor_initialized

tensor([[0.0465, 0.9748, 0.3298],
        [0.6207, 0.5597, 0.7289]])

In [9]:
tensor_initialized = torch.rand(2,3).type(torch.IntTensor)
tensor_initialized

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [11]:
# byte tensor
t2 = torch.ByteTensor([0,265,1,-5])
t2

tensor([  0,   9,   1, 251], dtype=torch.uint8)

In [12]:
# long tensor
t2 = torch.LongTensor([0,265,1,-5])
t2

tensor([  0, 265,   1,  -5])

In [14]:
tensor_initialized = torch.rand(2,3).type(torch.LongTensor)
tensor_initialized

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
t2 = torch.ones(10)
t2

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
t2 = torch.zeros(5,5)
t2

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [18]:
t2 = torch.eye(5)
t2


tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [19]:
t2 = t2.add(3)
t2

tensor([[4., 3., 3., 3., 3.],
        [3., 4., 3., 3., 3.],
        [3., 3., 4., 3., 3.],
        [3., 3., 3., 4., 3.],
        [3., 3., 3., 3., 4.]])

In [20]:
t2.add_(1)
t2

tensor([[5., 4., 4., 4., 4.],
        [4., 5., 4., 4., 4.],
        [4., 4., 5., 4., 4.],
        [4., 4., 4., 5., 4.],
        [4., 4., 4., 4., 5.]])

In [21]:
import numpy as np

In [23]:
np2 = np.array([1,2,3])
np2

array([1, 2, 3])

In [25]:
t2 = torch.from_numpy(np2)
t2

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
np2[1]=44
np2

array([ 1, 44,  3])

In [27]:
t2

tensor([ 1, 44,  3], dtype=torch.int32)

In [28]:
t2[2]=55
t2

tensor([ 1, 44, 55], dtype=torch.int32)

In [29]:
np2

array([ 1, 44, 55])

In [35]:
t2=torch.rand(4,5)
t2.size()

torch.Size([4, 5])

In [36]:
t2.shape

torch.Size([4, 5])

In [37]:
t3 = t2.view(-1,2)
t3.shape

torch.Size([10, 2])

In [43]:
t3

tensor([[0.0219, 0.3668],
        [0.7708, 0.9240],
        [0.6679, 0.9013],
        [0.8247, 0.6041],
        [0.9838, 0.4643],
        [0.3900, 0.8857],
        [0.0238, 0.4190],
        [0.3778, 0.0327],
        [0.2535, 0.0408],
        [0.7116, 0.1722]])

In [44]:
sorted_tensor, sorted_indices = torch.sort(t3, dim=0)

In [45]:
sorted_tensor

tensor([[0.0219, 0.0327],
        [0.0238, 0.0408],
        [0.2535, 0.1722],
        [0.3778, 0.3668],
        [0.3900, 0.4190],
        [0.6679, 0.4643],
        [0.7116, 0.6041],
        [0.7708, 0.8857],
        [0.8247, 0.9013],
        [0.9838, 0.9240]])