In [95]:
# from https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

In [97]:
import torch
import numpy as np

### Tensor Initialization
Tensors can be initialized in varioius ways

In [98]:
# Directly from data
data = [[1,2,],[3,4]]
x_data = torch.tensor(data)

In [100]:
# from numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [101]:
# from another tensor
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7206, 0.7514],
        [0.9795, 0.7714]]) 



In [103]:
# With random or constant values
# shape is a tuple of tensor dimensions.
shape=(2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeors_tensor = torch.zeros(shape)

# Tensor Attributes
Tensor attributes describe shape, datatype and device on which they are stored

In [108]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensore is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensore is stored on: cpu


# Tensor Operations
Over 100 operations - transpose, indexing, slicing, math, linear algebra, random sampling are at

https://pytorch.org/docs/stable/torch.html


In [110]:
torch.cuda.is_available()

True

In [111]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is storedon: {tensor.device}")

Device tensor is storedon: cuda:0


In [112]:
# Standard numpy-like indexing and slicing:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [114]:
# Joining tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [116]:
# Multiplying tensors (element-wise product)
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

                               

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [118]:
# Multiplying tensors (matrix multiply)
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [119]:
# In-place operations - have a _ suffice e.g. x.copy_(y) will change "x"
# note they lose history - so discouraged...
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Bridge with NumPy
Tensors on CPU and NumPy arrahs can share underlyinbg memory locations - changing one will change the other

In [121]:
# Tensor to NumPy array
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")


t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [122]:
# a change in the tensor shows up in the NumPy array
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [125]:
# NumPy array to Tensor
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
